[package]
name = "web_server"
version = "0.1.0"
edition = "2021"

[lib]
name = "thread_pool"
path = "src/lib.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
